# Generated by Django 3.2.3 on 2021-11-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
