# Generated by Django 3.2.3 on 2021-11-11 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_processor', '0002_alter_eventmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='payloadmodel',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='event_processor.eventmodel'),
        ),
    ]
