# Generated by Django 3.2.3 on 2021-11-11 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_processor', '0003_payloadmodel_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payloadmodel',
            name='element',
        ),
        migrations.RemoveField(
            model_name='payloadmodel',
            name='form',
        ),
        migrations.RemoveField(
            model_name='payloadmodel',
            name='host',
        ),
        migrations.RemoveField(
            model_name='payloadmodel',
            name='path',
        ),
        migrations.AlterField(
            model_name='payloadmodel',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='event_processor.categorymodel'),
        ),
        migrations.CreateModel(
            name='CaterogyFieldsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='event_processor.categorymodel')),
            ],
        ),
    ]
