# Generated by Django 3.2.3 on 2021-11-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_processor', '0004_auto_20211111_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='category',
        ),
    ]
