# Generated by Django 3.2.3 on 2021-11-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_processor', '0005_remove_eventmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payloadmodel',
            name='name',
        ),
    ]
