# Generated by Django 3.2.3 on 2021-11-11 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_processor', '0007_auto_20211111_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='payloadmodel',
            name='caterogy_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_processor.caterogyfieldsmodel'),
        ),
        migrations.AddField(
            model_name='payloadmodel',
            name='value',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='caterogyfieldsmodel',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='event_processor.categorymodel'),
        ),
    ]
