# Generated by Django 3.2.3 on 2021-11-11 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_processor', '0008_auto_20211111_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='payload',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_processor.payloadmodel'),
        ),
    ]
